stages:
  - build
  - build_image

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs/${CI_JOB_ID}"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "/certs/${CI_JOB_ID}/client"
  DOCKER_VERSION: "20.03"

build:
  image: mcr.microsoft.com/dotnet/sdk:6.0
  stage: build
  before_script:
    - dotnet restore
  script:
    - dotnet publish -c Release -o out
  artifacts:
    paths:
      - out
    expire_in: 1 hour

build_image:
  image: docker:git
  stage: build_image
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PW
    - docker tag $CI_REGISTRY_IMAGE:latest fusonic/git-backup:latest
    - docker push fusonic/git-backup:latest
  only:
    - main